# Increase debounce on central side to allow peripheral events to arrive
# Formula: (intervalMin + intervalMax) / 2 / 2 = (6 + 12) / 2 / 2 = 4.5ms
# Using 5ms to be safe
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10
